Get class directly
bkroeker/temporal_tables pull request #24
Opened 2023-01-25 05:32 UTC by evman182

2023-12-29 06:08 UTC, bkroeker commented
Looks good. Can you add a test for this case, please?

2023-12-29 06:10 UTC, bkroeker requested changes
Add test please

2024-01-03 16:56 UTC, bkroeker approved these changes

2024-01-03 16:56 UTC, bkroeker commented
@evman182 Looks great, thanks for all the cleanup!

2024-01-03 17:21 UTC, evman182 commented
@bkroeker  This is meant to followup https://github.com/bkroeker/temporal_tables/pull/29, but if you're good with all of it, I can merge it all together

2024-01-03 18:00 UTC, bkroeker commented
@evman182  Separate commits sounds good.

2024-01-03 18:46 UTC, merged